#1
FROM amazonlinux:latest

# 2
LABEL maintainer="afty.iitr@gmail.com"

# 3 
ARG JMETER_VERSION="4.0"

# 4
ENV JMETER_HOME /opt/apache-jmeter-${JMETER_VERSION}
ENV JMETER_BIN  ${JMETER_HOME}/bin
ENV MIRROR_HOST http://mirrors.ocf.berkeley.edu/apache/jmeter
ENV JMETER_DOWNLOAD_URL ${MIRROR_HOST}/binaries/apache-jmeter-${JMETER_VERSION}.tgz
ENV JMETER_PLUGINS_DOWNLOAD_URL http://repo1.maven.org/maven2/kg/apc
ENV JMETER_PLUGINS_FOLDER ${JMETER_HOME}/lib/ext/
ENV JMETER_LOG /opt/log

# 5
RUN yum -y update \
    && yum -y install tar \
    && yum -y install gzip \
    && yum -y install java \
    && yum -y install awscli \
    && mkdir -p /tmp/dependencies  \
	&& curl -L --silent ${JMETER_DOWNLOAD_URL} >  /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz  \
	&& mkdir -p /opt  \
    && mkdir -p /opt/log  \
	&& tar -xzf /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz -C /opt  \
	&& rm -rf /tmp/dependencies \
    && chmod 777 ${JMETER_BIN}/jmeter.sh    

# 6
RUN curl -L --silent ${JMETER_PLUGINS_DOWNLOAD_URL}/jmeter-plugins-dummy/0.2/jmeter-plugins-dummy-0.2.jar -o ${JMETER_PLUGINS_FOLDER}/jmeter-plugins-dummy-0.2.jar
RUN curl -L --silent ${JMETER_PLUGINS_DOWNLOAD_URL}/jmeter-plugins-cmn-jmeter/0.5/jmeter-plugins-cmn-jmeter-0.5.jar -o ${JMETER_PLUGINS_FOLDER}/jmeter-plugins-cmn-jmeter-0.5.jar

# 7 copy addition and custom lib external lib to lib/ext
ADD lib/ext ${JMETER_PLUGINS_FOLDER}
ADD bin  ${JMETER_BIN}
ADD scripts ${JMETER_HOME}/scripts

# 8
ENV PATH $PATH:$JMETER_BIN

# 9
WORKDIR ${JMETER_HOME}

#### how to use ############
#   Keep all external library in  lib/ext
#   Keep all groovy or beanshell script in bin.
#   update base jmeter image if new library or script is added
#   confirm locally if all require scripts and jar files are copy and then push base image to ECR or dockerhub
#   docker run -it jmeter-4.0 /bin/bash
#   pwd output should be JMETER_HOME
#   /opt/apache-jmeter-4.0
#   cd lib/ext or cd bin
#   ls -lrt and confirm 
